#!/bin/bash

# APK Billing Configuration Wizard
# Interactive setup script untuk konfigurasi mudah

clear
echo "🧙‍♂️ APK Billing Configuration Wizard"
echo "========================================="
echo ""
echo "Script ini akan membantu Anda mengkonfigurasi sistem APK Billing"
echo "sesuai dengan kebutuhan bisnis Anda."
echo ""

# Fungsi untuk input dengan default value
input_with_default() {
    local prompt="$1"
    local default="$2"
    local result
    
    echo -n "$prompt [$default]: "
    read result
    echo "${result:-$default}"
}

# Fungsi untuk yes/no input
yes_no_input() {
    local prompt="$1"
    local default="$2"
    local result
    
    while true; do
        echo -n "$prompt (y/n) [$default]: "
        read result
        result="${result:-$default}"
        case $result in
            [Yy]* ) echo "true"; break;;
            [Nn]* ) echo "false"; break;;
            * ) echo "Please answer y or n.";;
        esac
    done
}

# Pilih environment
echo "🌍 Environment Setup"
echo "==================="
echo "1. Development (untuk testing dan development)"
echo "2. Production (untuk sistem live)"
echo ""
echo -n "Pilih environment (1/2) [1]: "
read env_choice
env_choice="${env_choice:-1}"

if [ "$env_choice" = "2" ]; then
    ENVIRONMENT="production"
    ENV_FILE="backend/.env"
    FRONTEND_ENV_FILE="admin-panel/.env"
    echo "✅ Environment: Production"
else
    ENVIRONMENT="development"
    ENV_FILE="backend/.env"
    FRONTEND_ENV_FILE="admin-panel/.env"
    echo "✅ Environment: Development"
fi

echo ""

# Business Information
echo "🏢 Informasi Bisnis"
echo "=================="
BUSINESS_NAME=$(input_with_default "Nama Warnet/Cafe" "Warnet & Cafe ABC")
BUSINESS_ADDRESS=$(input_with_default "Alamat" "Jl. Raya No. 123, Jakarta")
BUSINESS_PHONE=$(input_with_default "Nomor Telepon" "021-12345678")
BUSINESS_EMAIL=$(input_with_default "Email" "info@warnetabc.com")

echo ""

# Database Configuration
echo "🗄️ Konfigurasi Database"
echo "======================"
if [ "$ENVIRONMENT" = "production" ]; then
    DB_HOST=$(input_with_default "Database Host" "postgres")
    DB_PASSWORD=$(input_with_default "Database Password" "$(openssl rand -base64 16)")
else
    DB_HOST="localhost"
    DB_PASSWORD="dev_password"
fi

DB_NAME=$(input_with_default "Nama Database" "apkbilling")
DB_USER=$(input_with_default "Database User" "apkbilling_user")

echo ""

# TV Configuration
echo "📺 Konfigurasi TV Billing"
echo "========================="
MAX_TV_SESSIONS=$(input_with_default "Maksimal TV bersamaan" "50")
SESSION_WARNING_MINUTES=$(input_with_default "Warning sebelum habis (menit)" "5")
AUTO_POWER_OFF=$(yes_no_input "Auto matikan TV saat habis?" "y")
MIN_BILLING_TIME=$(input_with_default "Minimum billing time (menit)" "30")

echo ""

# Pricing Configuration  
echo "💰 Konfigurasi Harga"
echo "==================="
CURRENCY=$(input_with_default "Mata uang" "IDR")
CURRENCY_SYMBOL=$(input_with_default "Simbol mata uang" "Rp")
TAX_RATE=$(input_with_default "Pajak (0.11 = 11%)" "0.11")
SERVICE_CHARGE=$(input_with_default "Biaya layanan (0.05 = 5%)" "0.05")

echo ""

# Network Configuration
echo "📡 Konfigurasi Network"
echo "===================="
WIFI_NAME=$(input_with_default "Nama WiFi" "Warnet_WiFi")
WIFI_PASSWORD=$(input_with_default "Password WiFi" "password123")
TV_NETWORK_RANGE=$(input_with_default "Range IP TV" "192.168.1.0/24")

echo ""

# Security Configuration
echo "🔐 Konfigurasi Keamanan"
echo "======================"
if [ "$ENVIRONMENT" = "production" ]; then
    JWT_SECRET=$(input_with_default "JWT Secret (min 32 karakter)" "$(openssl rand -base64 32)")
    ADMIN_PASSWORD=$(input_with_default "Password Admin" "$(openssl rand -base64 12)")
else
    JWT_SECRET="dev-jwt-secret-key-not-for-production"
    ADMIN_PASSWORD="admin123"
fi

ADMIN_USERNAME=$(input_with_default "Username Admin" "admin")

echo ""

# Advanced Configuration
echo "⚙️ Konfigurasi Lanjutan"
echo "======================"
ENABLE_BACKUP=$(yes_no_input "Enable auto backup?" "y")
ENABLE_NOTIFICATIONS=$(yes_no_input "Enable email notifications?" "n")

if [ "$ENABLE_NOTIFICATIONS" = "true" ]; then
    SMTP_HOST=$(input_with_default "SMTP Host" "smtp.gmail.com")
    SMTP_USER=$(input_with_default "SMTP User" "your-email@gmail.com")
    SMTP_PASS=$(input_with_default "SMTP Password" "your-app-password")
fi

echo ""

# Generate Configuration Files
echo "📝 Generating configuration files..."

# Generate Backend .env
cat > "$ENV_FILE" << EOF
# ================================
# APK BILLING SYSTEM - $(echo $ENVIRONMENT | tr '[:lower:]' '[:upper:]')
# Generated by Configuration Wizard
# $(date)
# ================================

# ================================
# DATABASE CONFIGURATION
# ================================
DB_HOST=$DB_HOST
DB_PORT=5432
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD
DB_MAX_CONNECTIONS=20
DB_CONNECTION_TIMEOUT=2000

# ================================
# REDIS CONFIGURATION
# ================================
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=
REDIS_DB=0
REDIS_KEY_PREFIX=apkbilling:

# ================================
# SERVER CONFIGURATION
# ================================
PORT=3000
NODE_ENV=$ENVIRONMENT
API_VERSION=v1
CORS_ORIGIN=*
REQUEST_TIMEOUT=30000

# ================================
# SECURITY CONFIGURATION
# ================================
JWT_SECRET=$JWT_SECRET
JWT_EXPIRES_IN=7d
JWT_REFRESH_EXPIRES_IN=30d
BCRYPT_ROUNDS=12
SESSION_TIMEOUT=3600

# Admin credentials
DEFAULT_ADMIN_USERNAME=$ADMIN_USERNAME
DEFAULT_ADMIN_PASSWORD=$ADMIN_PASSWORD
DEFAULT_ADMIN_NAME=System Administrator

# ================================
# BUSINESS CONFIGURATION
# ================================
BUSINESS_NAME=$BUSINESS_NAME
BUSINESS_ADDRESS=$BUSINESS_ADDRESS
BUSINESS_PHONE=$BUSINESS_PHONE
BUSINESS_EMAIL=$BUSINESS_EMAIL
BUSINESS_WEBSITE=

# Currency & Pricing
CURRENCY=$CURRENCY
CURRENCY_SYMBOL=$CURRENCY_SYMBOL
TAX_RATE=$TAX_RATE
SERVICE_CHARGE=$SERVICE_CHARGE
DECIMAL_PLACES=0

# Working Hours
WORKING_HOURS_START=08:00
WORKING_HOURS_END=23:00
TIMEZONE=Asia/Jakarta

# ================================
# TV BILLING CONFIGURATION
# ================================
MAX_TV_SESSIONS=$MAX_TV_SESSIONS
SESSION_WARNING_MINUTES=$SESSION_WARNING_MINUTES
AUTO_POWER_OFF=$AUTO_POWER_OFF
MIN_BILLING_TIME=$MIN_BILLING_TIME
GRACE_PERIOD_SECONDS=30
TV_MONITOR_INTERVAL=10

# ================================
# NETWORK CONFIGURATION
# ================================
WIFI_NAME=$WIFI_NAME
WIFI_PASSWORD=$WIFI_PASSWORD
TV_NETWORK_RANGE=$TV_NETWORK_RANGE
TV_DISCOVERY_PORT=8888
TV_COMMAND_PORT=8889

# ================================
# FILE UPLOAD CONFIGURATION
# ================================
UPLOAD_PATH=./uploads
MAX_FILE_SIZE=5242880
ALLOWED_FILE_TYPES=jpg,jpeg,png,gif,pdf,doc,docx
UPLOAD_URL_PREFIX=/uploads

# ================================
# POS SYSTEM CONFIGURATION
# ================================
ORDER_PREFIX=ORD
ORDER_NUMBER_LENGTH=8
RECEIPT_FOOTER=Terima kasih atas kunjungan Anda!
PRINT_LOGO=true
PRINT_QR_CODE=true
LOW_STOCK_THRESHOLD=10
AUTO_REORDER=false

# ================================
# BACKUP CONFIGURATION
# ================================
BACKUP_ENABLED=$ENABLE_BACKUP
BACKUP_SCHEDULE=0 2 * * *
BACKUP_RETENTION_DAYS=30
BACKUP_PATH=./backups

# ================================
# LOGGING CONFIGURATION
# ================================
LOG_LEVEL=info
LOG_FILE_PATH=./logs
LOG_DATABASE_QUERIES=false
LOG_API_REQUESTS=true
LOG_TV_EVENTS=true
LOG_TRANSACTIONS=true

# ================================
# DEVELOPMENT CONFIGURATION
# ================================
DEV_ENABLE_SEED_DATA=true
ENABLE_API_DOCS=true
DEBUG_MODE=false
EOF

# Add SMTP configuration if enabled
if [ "$ENABLE_NOTIFICATIONS" = "true" ]; then
    cat >> "$ENV_FILE" << EOF

# ================================
# NOTIFICATION CONFIGURATION
# ================================
SMTP_HOST=$SMTP_HOST
SMTP_PORT=587
SMTP_USER=$SMTP_USER
SMTP_PASS=$SMTP_PASS
SMTP_FROM_NAME=$BUSINESS_NAME
SMTP_FROM_EMAIL=noreply@apkbilling.com
EOF
fi

# Generate Frontend .env
cat > "$FRONTEND_ENV_FILE" << EOF
# ================================
# ADMIN PANEL - $(echo $ENVIRONMENT | tr '[:lower:]' '[:upper:]')
# Generated by Configuration Wizard
# $(date)
# ================================

# API Configuration
REACT_APP_API_URL=http://localhost:3000/api
REACT_APP_SOCKET_URL=http://localhost:3000

# Application
REACT_APP_NAME=APK Billing Admin
REACT_APP_ENV=$ENVIRONMENT
REACT_APP_BUSINESS_NAME=$BUSINESS_NAME

# UI Configuration
REACT_APP_CURRENCY_SYMBOL=$CURRENCY_SYMBOL
REACT_APP_CURRENCY_LOCALE=id-ID
REACT_APP_DEFAULT_PAGE_SIZE=25

# Features
REACT_APP_ENABLE_TV_MANAGEMENT=true
REACT_APP_ENABLE_POS_SYSTEM=true
REACT_APP_ENABLE_REPORTS=true
REACT_APP_ENABLE_SETTINGS=true
REACT_APP_ENABLE_DARK_MODE=true
REACT_APP_ENABLE_REALTIME=true

# Real-time Updates
REACT_APP_DASHBOARD_REFRESH_INTERVAL=5000
REACT_APP_TV_STATUS_REFRESH_INTERVAL=3000

# Security
REACT_APP_SESSION_TIMEOUT=60
REACT_APP_MIN_PASSWORD_LENGTH=8
EOF

echo ""
echo "✅ Configuration files generated successfully!"
echo ""
echo "📁 Files created:"
echo "   - $ENV_FILE"
echo "   - $FRONTEND_ENV_FILE"
echo ""

# Summary
echo "📋 Configuration Summary"
echo "======================="
echo "Environment: $ENVIRONMENT"
echo "Business: $BUSINESS_NAME"
echo "Max TV Sessions: $MAX_TV_SESSIONS"
echo "Admin Username: $ADMIN_USERNAME"
echo "Admin Password: $ADMIN_PASSWORD"
echo "Database: $DB_NAME"
echo "WiFi Name: $WIFI_NAME"
echo ""

echo "⚠️  IMPORTANT NOTES:"
echo "1. Backup your .env files"
echo "2. Change admin password after first login"
echo "3. Review all settings before going to production"
echo "4. Never commit .env files to version control"
echo ""

# Ask to start system
start_system=$(yes_no_input "Start the system now?" "y")

if [ "$start_system" = "true" ]; then
    echo ""
    echo "🚀 Starting APK Billing System..."
    
    if [ "$ENVIRONMENT" = "production" ]; then
        ./scripts/prod-deploy.sh
    else
        ./scripts/dev-setup.sh
    fi
else
    echo ""
    echo "System not started. To start manually:"
    if [ "$ENVIRONMENT" = "production" ]; then
        echo "  sudo ./scripts/prod-deploy.sh"
    else
        echo "  ./scripts/dev-setup.sh"
    fi
fi

echo ""
echo "🎉 Configuration wizard completed!"
echo "Visit: http://localhost:3001 (development) or http://localhost:8080 (production)"
echo ""
echo "Default login:"
echo "Username: $ADMIN_USERNAME"
echo "Password: $ADMIN_PASSWORD"
echo ""
echo "📖 For more configuration options, see CONFIG_GUIDE.md"